import path from "path";
import { fileURLToPath } from "url";
import webpack from "webpack";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Generate build date and time
const buildDate = new Date().toISOString();

export default {
  mode: "development",
  entry: {
    'custom-embedding': "./index.ts"
  },
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "[name].js",
    library: {
      type: "module",
    },
  },
  experiments: {
    outputModule: true,
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        use: "ts-loader",
        exclude: /node_modules/,
      },
    ],
  },
  resolve: {
    extensions: [".ts", ".js"],
  },
  plugins: [
    // Add build date and time as a banner to the output file
    new webpack.BannerPlugin({
      banner: `Build Date: ${buildDate}
Generated by GitHub Copilot`,
      entryOnly: true
    }),
  ],
};