# Github action to build and publish to GitHub Releases
name: Build and Publish ES Module to GitHub Releases
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Add permissions needed for creating releases
permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@TrustedResearchEnvironment'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build project
        run: npm run build
        
      # Publish to GitHub Packages
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Get version from package.json
      - name: Get version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      
      # Create GitHub Release and upload asset
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.package-version.outputs.current-version }}
          name: Release v${{ steps.package-version.outputs.current-version }}
          body: |
            ## Webpack TypeScript Embeddings Library
            
            ### Installation
            
            Import as an ES module:
            ```html
            <script type="module">
              import { definition } from 'https://github.com/TrustedResearchEnvironment/webpack-ts-example/releases/download/v${{ steps.package-version.outputs.current-version }}/custom-embedding.js';
              // Use the library...
            </script>
            ```
          files: |
            ./dist/custom-embedding.js
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}